spring:
  messages:
    basename: messages/messages   # internationalization
  test:
    database.replace: none
  thymeleaf:
    mode: HTML
  web:
    resources.cache:
      cachecontrol:
        max-age: 12h            # maximum time static resources should be cached

yugabyte:
  datasource:
    # url: jdbc:postgresql://127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433/yugabyte
    url: jdbc:postgresql://8bd2c228-de3c-4808-8a99-xxxxxxxxx.cloudportal.yugabyte.com:5433/petclinic?ssl=true&sslmode=verify-full
    load-balance: true
    username: admin
    password: 

management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"

# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte.data.jdbc: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  #org.springframework.web: DEBUG
  #org.springframework.context.annotation: TRACE
