# Using Yugabyte's test container
yugabyte:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:yugabyte://localhost/myappdb
    username: user
    password: postgres
