# use test containers t
yugabyte:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://localhost/myappdb
    username: user
    password: postgres
